version: '3.8'

services:
  app:
    image: devmikroblog
    ports: 
      - 5005:80
    environment: 
      - RabbitMq__AmqpConnection=amqp://guest:guest@rabbitmq:5672
      - ConnectionStrings__PostsDb=Host=db;Port=5432;User Id=postgres;Password=postgres;Database=postgres;
      - Seq__Url=http://seq:5341
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - "db"
      - "seq"
      - "rabbitmq"


  db:
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  seq:
    image: datalust/seq 
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    depends_on:
      - "rabbitmq"
      
  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    depends_on:
      - "rabbitmq"
volumes:
  postgres-data: null
