version: '3.8'

services:
  app:
    image: devmikroblog
    ports: 
      - 5005:80
    environment: 
      - RabbitMq__AmqpConnection=amqp://guest:guest@rabbitmq:5672
      - ConnectionStrings__PostsDb=Host=db;Port=5432;User Id=postgres;Password=postgres;Database=postgres;
      - Seq__Url=http://seq:5341
      - ASPNETCORE_ENVIRONMENT=Development
      - OTEL_COLLECTOR_URL=http://otel-collector:4317
    depends_on:
      - "db"
      - "seq"
      - "rabbitmq"
  db:
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  seq:
    image: datalust/seq 
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    depends_on:
      - "rabbitmq"
      
  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    depends_on:
      - "rabbitmq"
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411

  otel-collector:
    image: otel/opentelemetry-collector:0.48.0
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "9411"   # Zipkin receiver
      - "55679:55679" # zpages extension
      - "4317:4317"
    depends_on:
      - jaeger
      - zipkin
volumes:
  postgres-data: null
