@port = 53766 
@jwt_key = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJkZXYtbWlrcm9ibG9nIiwiaWF0IjoxNjU1OTEyNzY4LCJleHAiOjE3ODIxNDMxNjgsImF1ZCI6ImRldi1taWtyb2Jsb2ciLCJzdWIiOiJlZWUwZDNiNy0xZmI2LTRiMWEtOGM3OC1iODI3YjBiNjQ2NWIiLCJ1bmlxdWVfbmFtZSI6ImphbiBQYXdlxYIgMzMzIn0.LDf0JDIrQnmu8nIlNnlpq5fokKUQsvnXzfW7k-yFGA-ygZYI0Z6Q2pu7EDwq72h-oYpJJqJ6STQMGf18XC6nxQ

###

POST http://localhost:{{port}}/post
Content-Type: application/json
Authorization: Bearer {{jwt_key}}
Accept: application/json

{
  "content": "xDDD #fsharp"
}

### 

POST http://localhost:{{port}}/posts HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "page": 1,
  "pageSize": 12
}